### ISSUE TITLE
Need build instruction

### ISSUE THREAD

**Issue by hoaluvn** [fvutils/pyhdl-if#10]
Hi,

Could you please provide instructions to build and install this package?
I have tried several approaches but not success. Thanks!

**Comment by mballance** [comment]
Hi @hoaluvn,
    I've added a quickstart section to the docs (https://fvutils.github.io/pyhdl-if/quickstart.html). 
   The preferred way to install is via a pypi binary package (pip install pyhdl-if). Note that this will only work on Linux for now.
    Currently, only x86_64 Linux platforms are supported (https://fvutils.github.io/pyhdl-if/overview.html#status-and-roadmap). If you require different OS or architecture support, please file an enhancement request noting the OS, architecture, and simulator that you use.

-Matthew
