### ISSUE TITLE
Installing the library

### ISSUE THREAD

**Issue by marwan-ramzi** [fvutils/pyhdl-if#11]
I have python version 3.10.7 and pip version 24.3.1. I tried using this:
![image](https://github.com/user-attachments/assets/236f8430-ede9-4f94-b1fe-b9ab7170d16b)

And tried alternative method using pip and the repo:
![image](https://github.com/user-attachments/assets/356e302f-3bfd-43ba-8b8b-6adf45a614d7)
![image](https://github.com/user-attachments/assets/c2e59be2-ba44-400f-8eaf-c7eab40d0482)

**Comment by mballance** [comment]
Ah, I see. You're running on Windows. Currently, only Linux is supported (though other platforms are on the roadmap based on demand).

Are you able to use WSL (Windows Subsystem for Linux)? What HDL simulator do you use on Windows?

**Comment by marwan-ramzi** [comment]
I will try to use WSL and let you know. I am currently using ModelSim.

**Comment by marwan-ramzi** [comment]
I used WSL (installed Debian) and the library installed successfully.
![image](https://github.com/user-attachments/assets/bb43e75e-55f8-4df7-a8dd-f18eb52b82cb)
Although I would like to use pyhdl-if on Windows. Thanks for your time.

**Comment by mballance** [comment]
Thanks for confirming, @marwan-ramzi. I've opened an enhancement request (https://github.com/fvutils/pyhdl-if/issues/12). Feel free to watch and/or comment on that issue. Also, if you have colleagues that would also be interested in Windows support, have them comment on the issue as well.
