### ISSUE TITLE
Unable to load the default library libdpi

### ISSUE THREAD

**Issue by penguali** [fvutils/pyhdl-if#9]
I am wondering if the example in https://github.com/fvutils/pyhdl-if/tree/main/examples/call/cocotb/call_sv_bfm is also applicable in Xcelium from Cadence.

I'm trying to get the example working in Xcelium 23.09 but have had no success.

I made small adjustments in the Makefile so that I could use the Xcelium simulator and these two lines are now:
```makefile
SIM ?= xcelium
EXTRA_ARGS += +incdir+${HDL_IF_SHARE}/dpi
```
Then running `init_venv.sh`, activating the virtual environment, and then `make` would give the error from within xrun:
```
xmsim: *F,NOLWSV: Searching for import subroutine "_pyhdl_if_PyErr_BadArgument" in default library libdpi. Unable to load the default library libdpi.
OSDLERROR: ./libdpi.so: cannot open shared object file: No such file or directory or file is not valid ELFCLASS64 library..
```

So I did some digging and found a section in Cadence's SystemVerilog Reference that states that the path to the shared library must be included in the library path environment `LD_LIBRARY_PATH` and that SystemVerilog tasks and functions C objects must be compiled and linked to that shared library. I'm not sure if this is already handled here.

I also tried running `runit_xcm.sh`, but it kills my terminal session.

Any ideas what is going wrong here? I would appreciate the help.

I'm using:
- Oracle Linux 8.10
- Python 3.12.7
- I have also tried Python 3.10.15

**Comment by mballance** [comment]
Thanks for raising this, @penguali. It seems the example Makefile was only configured to support Verilator. I've updated the Makefile to support Xcelium and Questa. You should be able to do the following:
- Fetch the latest source for the example (the pyhdl-if library does not require an update)
- Activate the virtual environment
- run: `PYTHONPATH=$(pwd) make SIM=xcelium`

I'll close this issue for now. Feel free to re-open it or file a new one if you face more issues.

**Comment by penguali** [comment]
Thanks for replying! The issue is resolved. The test starts and it prints all the `read` and `write` interactions. 

However, the test is shutdown prematurely because of test errors from `cocotb.schedular` and `cocotb.regression`.
Just before the test shutdown, I could only see `read` commands being printed. I'm not sure if this is related to the problem.

Should it be opened as a new issue?

**Comment by mballance** [comment]
Ah, good catch @penguali. I did run into this issue and fixed it by extending the time-out in the SV testbench module. Unfortunately, I forgot to commit my changes. Changes are now pushed, so you shouldn't see the timeout now.
